package com.onk.grp2.WindTurbine.main;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.Timer;

import com.onk.grp2.WindTurbine.autoGenerated.WindTurbine;
import com.onk.grp2.WindTurbine.utilities.WindTurbinePublisher;
import com.onk.grp2.WindTurbine.utilities.WindTurbineSubscriber;

public class WindTurbineControlImpl implements WindTurbineControl {
	
	private WindTurbinePublisher publisher = null;
	private WindTurbineSubscriber subscriber = null;
	
	public WindTurbineControlImpl(WindTurbinePublisher publisher, WindTurbineSubscriber subscriber) {
		if(publisher == null) {
			throw new IllegalArgumentException("Specify a publisher for the controller to use");
		}
		
		if(subscriber == null) {
			throw new IllegalArgumentException("Specify a subscriber for the controller to use");
		}
		
		this.publisher = publisher;
		this.subscriber = subscriber;
	}

	@Override
	public void run() {
		
	}

	@Override
	public void SendEvent(com.onk.grp2.WindTurbine.autoGenerated.WindTurbine status) {
		publisher.notify(status);
		
	}
}