package com.onk.grp2.WindTurbine.control;

import com.onk.grp2.Common.utilities.WindTurbinePublisher;
import com.onk.grp2.WindTurbine.driver.WindTurbineMeasurere;

public class WindTurbineControlImpl implements WindTurbineControl {
	
	private WindTurbinePublisher publisher = null;
	private WindTurbineMeasurere measurere = null;
	
	public WindTurbineControlImpl(WindTurbinePublisher publisher,  WindTurbineMeasurere measurere) {
		if(publisher == null) {
			throw new IllegalArgumentException("Specify a publisher for the controller to use");
		}
		
		if(measurere == null) {
			throw new IllegalArgumentException("Specify a Measurere driver for the controller to use");
		}
		
		this.publisher = publisher;
		this.measurere = measurere;
	}

	@Override
	public void run() {
		measurere.addWindTurbineEventListener(this);
	}

	@Override
	public void SendEvent(com.onk.grp2.Common.autoGenerated.WindTurbine status) {
		publisher.notify(status);
		
	}
}