package com.onk.grp2.WindTurbine.control;

import com.onk.grp2.Common.utilities.WindTurbinePublisher;
import com.onk.grp2.WindTurbine.driver.Display;
import com.onk.grp2.WindTurbine.driver.WindTurbineMeasurere;

public class WindTurbineControlImpl implements WindTurbineControl {
	
	private WindTurbinePublisher publisher = null;
	private WindTurbineMeasurere measurere = null;
	private Display display = null;
	
	public WindTurbineControlImpl(WindTurbinePublisher publisher,  WindTurbineMeasurere measurere, Display display) {
		if(publisher == null) {
			throw new IllegalArgumentException("Specify a publisher for the controller to use");
		}
		
		if(measurere == null) {
			throw new IllegalArgumentException("Specify a Measurere driver for the controller to use");
		}
		
		if(display == null) {
			throw new IllegalArgumentException("Specify a display driver for the controller to use");
		}
		
		this.publisher = publisher;
		this.measurere = measurere;
		this.display = display;
	}

	@Override
	public void run() {
		measurere.addWindTurbineEventListener(this);
		measurere.run();
	}

	@Override
	public void SendEvent(com.onk.grp2.Common.autoGenerated.WindTurbine status) {
		display.putText(status.toString());
		publisher.notify(status);
		
	}
}