package com.onk.grp2.Environment.main;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.Timer;

import com.onk.grp2.Environment.autoGenerated.Environment;
import com.onk.grp2.Environment.utilities.EnvironmentPublisher;
import com.onk.grp2.Environment.utilities.EnvironmentSubscriber;

public class EnvironmentControlImpl implements EnvironmentControl {
	
	private EnvironmentPublisher publisher = null;
	private EnvironmentSubscriber subscriber = null;
	
	public EnvironmentControlImpl(EnvironmentPublisher publisher, EnvironmentSubscriber subscriber) {
		if(publisher == null) {
			throw new IllegalArgumentException("Specify a publisher for the controller to use");
		}
		
		if(subscriber == null) {
			throw new IllegalArgumentException("Specify a subscriber for the controller to use");
		}
		
		this.publisher = publisher;
		this.subscriber = subscriber;
	}

	@Override
	public void run() {
		
	}

	@Override
	public void SendEvent(Environment status) {
		publisher.notify(status);
		
	}

}
