package com.onk.grp2.Evironment.control;

import com.onk.grp2.Common.autoGenerated.Environment;
import com.onk.grp2.Common.utilities.EnvironmentPublisher;

public class EnvironmentControlImpl implements EnvironmentControl {
	
	private EnvironmentPublisher publisher = null;
	
	public EnvironmentControlImpl(EnvironmentPublisher publisher) {
		if(publisher == null) {
			throw new IllegalArgumentException("Specify a publisher for the controller to use");
		}
		
		this.publisher = publisher;
	}

	@Override
	public void run() {
		for(;;);
	}

	@Override
	public void SendEvent(Environment status) {
		publisher.notify(status);
		
	}

}
