package com.onk.grp2.Evironment.control;

import com.onk.grp2.Common.autoGenerated.Environment;
import com.onk.grp2.Common.utilities.EnvironmentPublisher;
import com.onk.grp2.Environment.driver.EnvironmentMeasurere;

public class EnvironmentControlImpl implements EnvironmentControl {
	
	private EnvironmentPublisher publisher = null;
	private EnvironmentMeasurere measurere = null;
	
	public EnvironmentControlImpl(EnvironmentPublisher publisher, EnvironmentMeasurere measurere) {
		if(publisher == null) {
			throw new IllegalArgumentException("Specify a publisher for the controller to use");
		}
		
		if(measurere == null) {
			throw new IllegalArgumentException("Specify a measurere for the controller to use");
		}
		
		this.publisher = publisher;
		this.measurere = measurere;
	}

	@Override
	public void run() {
		measurere.addEnvironmentEventListener(this);
		measurere.run();
	}

	@Override
	public void SendEvent(Environment status) {
		System.out.println("Sending wind data");
		publisher.notify(status);
		
	}

}
