package com.onk.grp2.Enviroment.main;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.Timer;

import onk.grp2.WindTurbine.autoGenerated.WindTurbine;
import onk.grp2.WindTurbine.utilities.WindTurbinePublisher;
import onk.grp2.WindTurbine.utilities.WindTurbineSubscriber;

public class EnvironmentControlImpl implements EnvironmentControl {
	
	private WindTurbinePublisher publisher = null;
	private WindTurbineSubscriber subscriber = null;
	
	public EnvironmentControlImpl(WindTurbinePublisher publisher, WindTurbineSubscriber subscriber) {
		if(publisher == null) {
			throw new IllegalArgumentException("Specify a publisher for the controller to use");
		}
		
		if(subscriber == null) {
			throw new IllegalArgumentException("Specify a subscriber for the controller to use");
		}
		
		this.publisher = publisher;
		this.subscriber = subscriber;
	}

	@Override
	public void run() {
		
	}

	@Override
	public void SendEvent(WindTurbine status) {
		publisher.notify(status);
		
	}

}
