package com.onk.grp2.Common.utilities;

import com.onk.grp2.Common.autoGenerated.Environment;

/**
 * 
 * @author sune
 * Interface used for callbacks when data are received on the environment topic
 */
public interface EnvironmentReceiver {
	public void updateEnvironment(Environment windData);

}
