package com.onk.grp2.Common.utilities;

import com.onk.grp2.Common.autoGenerated.WindTurbine;

public interface WindTurbineReceiver {
	public void updateWindTurbineData(WindTurbine windTurbineData);

}
