struct WindTurbine {
	long										 id;
    float							             orientation;
    float                                        bladePitch;
    float										 RPM;
    float										 temperature;
    float										 production;
};
