package com.onk.grp2.DataConsumer.control;

import com.onk.grp2.Common.autoGenerated.WindTurbine;

/**
 * 
 * @author sune
 *
 */

public class DataConsumerControlImpl implements DataConsumerControl{
	
	public DataConsumerControlImpl() {
	}

	@Override
	public void updateWindTurbineData(WindTurbine windTurbineData) {
		System.out.println(windTurbineData.toString());
		
	}

}